[package]
name = "wifi-connect"
version = "0.1.0"
edition = "2024"

[lib]
name = "wifi_connect"
path = "src/lib.rs"

[dependencies]

[dev-dependencies]
tempfile = "3.8"

[[bin]]
name = "wifi-connect"
path = "src/main.rs"
